spring:
  application:
    name: api-gateway

server:
  port: 8765

#currency-exchange-service:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  sensitive-headers: Cookie, set-Cookie
#zuul:
#  prefix:  /api
#  routes:
#    # 수동 경로 매핑  http://localhost:5555/srve2/v1/~~
#    currency-exchange-service: /exchange/**


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/