server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.216.32.5:3721/bom-bems?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: vetec3721
  jpa:
    hibernate:
      ddl-auto: none
      use_aql_comments: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org:
    hibernate:
      SQL: debug
      type: trace
